# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CmonitorAgent < Formula
  desc "Agent for CMonitor, a lightweight server monitoring platform."
  homepage "https://cmonitor.dev"
  version "0.11.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nguyendkn/cmonitor/releases/download/v0.11.2/cmonitor-agent_darwin_amd64.tar.gz"
      sha256 "d1ace8a56b5ed0559618e0e031a63ee24f3fe3d18ca0ee8076a02f13850b622d"

      def install
        bin.install "cmonitor-agent"
        (bin/"cmonitor-agent-launcher").write <<~EOS
          #!/bin/bash
          set -a
          if [ -f "$HOME/.config/cmonitor/cmonitor-agent.env" ]; then
            source "$HOME/.config/cmonitor/cmonitor-agent.env"
          fi
          set +a
          exec #{bin}/cmonitor-agent "$@"
        EOS
        (bin/"cmonitor-agent-launcher").chmod 0755
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nguyendkn/cmonitor/releases/download/v0.11.2/cmonitor-agent_darwin_arm64.tar.gz"
      sha256 "a5a4083643d8ddf192387761e74aa8f2867ab43bf8d9e3b09d3179f44767b67d"

      def install
        bin.install "cmonitor-agent"
        (bin/"cmonitor-agent-launcher").write <<~EOS
          #!/bin/bash
          set -a
          if [ -f "$HOME/.config/cmonitor/cmonitor-agent.env" ]; then
            source "$HOME/.config/cmonitor/cmonitor-agent.env"
          fi
          set +a
          exec #{bin}/cmonitor-agent "$@"
        EOS
        (bin/"cmonitor-agent-launcher").chmod 0755
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/nguyendkn/cmonitor/releases/download/v0.11.2/cmonitor-agent_linux_amd64.tar.gz"
      sha256 "fbd04f259c465e91fa4481175c3dfd7ff8b94ed564427d172bd2e445bfcdb923"
      def install
        bin.install "cmonitor-agent"
        (bin/"cmonitor-agent-launcher").write <<~EOS
          #!/bin/bash
          set -a
          if [ -f "$HOME/.config/cmonitor/cmonitor-agent.env" ]; then
            source "$HOME/.config/cmonitor/cmonitor-agent.env"
          fi
          set +a
          exec #{bin}/cmonitor-agent "$@"
        EOS
        (bin/"cmonitor-agent-launcher").chmod 0755
      end
    end
    if Hardware::CPU.arm? and !Hardware::CPU.is_64_bit?
      url "https://github.com/nguyendkn/cmonitor/releases/download/v0.11.2/cmonitor-agent_linux_arm.tar.gz"
      sha256 "b20a47d9c326da4d1ac60cccae2509cea423112c8e89747e5cc990d2f6b87f8b"
      def install
        bin.install "cmonitor-agent"
        (bin/"cmonitor-agent-launcher").write <<~EOS
          #!/bin/bash
          set -a
          if [ -f "$HOME/.config/cmonitor/cmonitor-agent.env" ]; then
            source "$HOME/.config/cmonitor/cmonitor-agent.env"
          fi
          set +a
          exec #{bin}/cmonitor-agent "$@"
        EOS
        (bin/"cmonitor-agent-launcher").chmod 0755
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/nguyendkn/cmonitor/releases/download/v0.11.2/cmonitor-agent_linux_arm64.tar.gz"
      sha256 "8963a6eca3cab4867b79520c04b11ff3076d0f0903659c72a8bc4e78ad024e4d"
      def install
        bin.install "cmonitor-agent"
        (bin/"cmonitor-agent-launcher").write <<~EOS
          #!/bin/bash
          set -a
          if [ -f "$HOME/.config/cmonitor/cmonitor-agent.env" ]; then
            source "$HOME/.config/cmonitor/cmonitor-agent.env"
          fi
          set +a
          exec #{bin}/cmonitor-agent "$@"
        EOS
        (bin/"cmonitor-agent-launcher").chmod 0755
      end
    end
  end

  service do
    run ["#{bin}/cmonitor-agent-launcher"]
    log_path "#{Dir.home}/.cache/cmonitor/cmonitor-agent.log"
    error_log_path "#{Dir.home}/.cache/cmonitor/cmonitor-agent.log"
    keep_alive true
  end
end
