# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CmonitorAgent < Formula
  desc "Agent for CMonitor, a lightweight server monitoring platform."
  homepage "https://cmonitor.dev"
  version "0.11.1-dev.18"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nguyendkn/cmonitor/releases/download/v0.11.1-dev.18/cmonitor-agent_darwin_amd64.tar.gz"
      sha256 "dee87bfd91b3a6bba3e63a46b71a6eb00f8641908b41083c822f97171de816d8"

      def install
        bin.install "cmonitor-agent"
        (bin/"cmonitor-agent-launcher").write <<~EOS
          #!/bin/bash
          set -a
          if [ -f "$HOME/.config/cmonitor/cmonitor-agent.env" ]; then
            source "$HOME/.config/cmonitor/cmonitor-agent.env"
          fi
          set +a
          exec #{bin}/cmonitor-agent "$@"
        EOS
        (bin/"cmonitor-agent-launcher").chmod 0755
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nguyendkn/cmonitor/releases/download/v0.11.1-dev.18/cmonitor-agent_darwin_arm64.tar.gz"
      sha256 "22bd38ad8c558618ffb99076f18c54d2171475cd4cf76bd472454c75ec61a251"

      def install
        bin.install "cmonitor-agent"
        (bin/"cmonitor-agent-launcher").write <<~EOS
          #!/bin/bash
          set -a
          if [ -f "$HOME/.config/cmonitor/cmonitor-agent.env" ]; then
            source "$HOME/.config/cmonitor/cmonitor-agent.env"
          fi
          set +a
          exec #{bin}/cmonitor-agent "$@"
        EOS
        (bin/"cmonitor-agent-launcher").chmod 0755
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/nguyendkn/cmonitor/releases/download/v0.11.1-dev.18/cmonitor-agent_linux_amd64.tar.gz"
      sha256 "c8f39ea819b7aac9260f60c820bfe64216a97747573519bba2499842c7b0ba41"
      def install
        bin.install "cmonitor-agent"
        (bin/"cmonitor-agent-launcher").write <<~EOS
          #!/bin/bash
          set -a
          if [ -f "$HOME/.config/cmonitor/cmonitor-agent.env" ]; then
            source "$HOME/.config/cmonitor/cmonitor-agent.env"
          fi
          set +a
          exec #{bin}/cmonitor-agent "$@"
        EOS
        (bin/"cmonitor-agent-launcher").chmod 0755
      end
    end
    if Hardware::CPU.arm? and !Hardware::CPU.is_64_bit?
      url "https://github.com/nguyendkn/cmonitor/releases/download/v0.11.1-dev.18/cmonitor-agent_linux_arm.tar.gz"
      sha256 "38f8891f3c0ce629193465e367519860b6533f9019283ae2f802c14ec33fc58f"
      def install
        bin.install "cmonitor-agent"
        (bin/"cmonitor-agent-launcher").write <<~EOS
          #!/bin/bash
          set -a
          if [ -f "$HOME/.config/cmonitor/cmonitor-agent.env" ]; then
            source "$HOME/.config/cmonitor/cmonitor-agent.env"
          fi
          set +a
          exec #{bin}/cmonitor-agent "$@"
        EOS
        (bin/"cmonitor-agent-launcher").chmod 0755
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/nguyendkn/cmonitor/releases/download/v0.11.1-dev.18/cmonitor-agent_linux_arm64.tar.gz"
      sha256 "99cb93757b971b6494acfb3612b8fe9e85388dd719f0b6f0bbaf240fcc44f262"
      def install
        bin.install "cmonitor-agent"
        (bin/"cmonitor-agent-launcher").write <<~EOS
          #!/bin/bash
          set -a
          if [ -f "$HOME/.config/cmonitor/cmonitor-agent.env" ]; then
            source "$HOME/.config/cmonitor/cmonitor-agent.env"
          fi
          set +a
          exec #{bin}/cmonitor-agent "$@"
        EOS
        (bin/"cmonitor-agent-launcher").chmod 0755
      end
    end
  end

  service do
    run ["#{bin}/cmonitor-agent-launcher"]
    log_path "#{Dir.home}/.cache/cmonitor/cmonitor-agent.log"
    error_log_path "#{Dir.home}/.cache/cmonitor/cmonitor-agent.log"
    keep_alive true
  end
end
